---

- name: Install Unattended Upgrades System Packages
  apt:
    pkg: unattended-upgrades
    state: present
    force: yes

- name: Place unattended upgrades config files
  copy: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=0600
  with_items:
    - { src: 50unattended-upgrades, dest: /etc/apt/apt.conf.d/50unattended-upgrades }
    - { src: 02periodic, dest: /etc/apt/apt.conf.d/02periodic }
